version: '3.7'
services:
  server:
    build: .
    depends_on:
      - db
    ports:
      - '3001:3001'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
    ports:
      - '5432:5432'
  socket:
    build: path/to/dockerfile
    ports:
      - '3002:3002'
  client:
    build: path/to/dockerfile
    depends_on:
      - server
      - socket
    ports:
      - '3000:3000'
